#!/usr/bin/env bash

usage() {
    cat << EOF
-s <size> | --size <size> - sets target size of output file in mb
-h        | --help        - this message
Everything else considered to be a file path
EOF
}

if [ -z "$1" ]; then
  usage
  exit
fi
ARGS=$(getopt -a -n resize -o s:h --long size,help -- "$@")
eval set -- "$ARGS"
while true; do
    case $1 in
        -s | --size) target_size_mb=$2  ; shift 2;;
        -h | --help) usage              ; exit;;
        --) shift; break;;
    esac
done

target_size_mb="${target_size_mb:-10}" # target size in MB
for file in "$@"; do
    file_name="$(basename "$file")"
    mime=$(file -b --mime-type "$file")
    ext="${file##*.}"
    if [[ "$mime" == video/* ]]; then
        size=$(( $(stat -c %s "$file") / 1024 / 1024 )) # file size in MB
        if (( size > target_size_mb * 8 )); then
            kdialog \
                --title "Compress Media: File is too big!" \
                --error "
«$(basename "$file")» is too big (${size}MB) for the target size of ${target_size_mb}MiB.
Input file must not be more than 8 times bigger than target size."
            exit 1
        fi
        if [ -f "${file%."${ext}"}-${target_size_mb}mb.${ext}" ]; then
            kdialog \
                --title "Compress Media" \
                --warningcontinuecancel "Output file already exists" || exit
        fi
        target_size=$(( target_size_mb * 1024 * 1024 * 8 )) # target size in bits
        length=$(ffprobe -v error -show_entries format=duration -of default=noprint_wrappers=1:nokey=1 "$file")
        length=$(( ${length%.*} + 1 ))
        total_bitrate=$(( target_size / length ))
        audio_bitrate=$(( 128 * 1000 )) # 128k bit rate
        video_bitrate=$(( total_bitrate - audio_bitrate ))
        trap 'rm "${TMPDIR:-/tmp}/ffmpeg2pass-$(basename "$file")"*' EXIT
        # -r sets output FPS
        # -vf "scale=-1:'min(1080,ih)'" if the image is higher than 1080p will rescale to 1080p
        ffmpeg -y -i "$file" \
            -vf "scale=-1:'min(1080,ih)'" \
            -r 60 \
            -c:v libx264 \
            -preset medium \
            -b:v $video_bitrate \
            -pass 1 \
            -passlogfile "${TMPDIR:-/tmp}/ffmpeg2pass-$file_name" \
            -b:a $audio_bitrate \
            -f "$ext" \
            /dev/null && \
        ffmpeg -y -i "$file" \
            -vf "scale=-1:'min(1080,ih)'" \
            -r 60 \
            -c:v libx264 \
            -preset medium \
            -b:v $video_bitrate \
            -pass 2 \
            -passlogfile "${TMPDIR:-/tmp}/ffmpeg2pass-$file_name" \
            -b:a $audio_bitrate \
            "${file%."${ext}"}-${target_size_mb}mb.${ext}"
    elif [[ "$mime" == image/* ]]; then
        magick "$file" \
            -define "webp:extent=$((target_size_mb * 1024))KB" \
            "${file%."${ext}"}-${target_size_mb}mb.webp"
    else
        kdialog --title "Compress Media" --error "Unsupported file type"
    fi
done
